name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_USERNAME }}" | docker login -u "${{ secrets.DOCKER_PASSWORD }}" --password-stdin

    - name: Build Docker image
      run: docker build -t 20031114/myapp:${{ github.sha }} .

    - name: Push Docker image
      run: docker push 20031114/myapp:${{ github.sha }}

    - name: Simulated Kubernetes Deployment (Minikube is local)
      run: echo "Simulating deployment to Kubernetes - Minikube not accessible from GitHub Actions"

    - name: Run basic test
      run: |
        echo "Simulating test of application endpoint (Minikube local access only)"
        echo "Expected test would curl localhost:8084 and verify response"